#
# Copyright (c) 2018 PSPDFKit GmbH. All rights reserved.
#
# The PSPDFKitSwift is licensed with a modified BSD license. Please see License for
# details. This notice may not be removed from this file.
#

platform :ios, '11.0'
use_frameworks!

pod 'PSPDFKitSwift', :git => 'https://github.com/PSPDFKit/PSPDFKit.swift.git', :tag => '1.0.0'

target 'PSPDFKitExample' do

  # Replace `_YOUR_COCOAPODS_KEY_` with your own.
  pod 'PSPDFKit/Swift', podspec: 'https://customers.pspdfkit.com/cocoapods/_YOUR_COCOAPODS_KEY_/latest.podspec'

end